import Header from '@/Components/Header';
import "@fortawesome/fontawesome-svg-core";
import { config } from "@fortawesome/fontawesome-svg-core";
import "./globals.css";
config.autoAddCss = false

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "social-logo/github-142-svgrepo-com.svg"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
